language: generic

services:
  - docker

  deploy:
    provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-2
    app: "cloudxlab-first-app-test"
    env: "Cloudxlabfirstapptest-env"
    bucket_name: "cloudxlab-first-app-to-be-deleted"
    on:
      branch: testing